import 'dart:convert';
import 'package:employeee/Model/Suggsetions_model.dart';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart'as http;
import 'package:shared_preferences/shared_preferences.dart';


  Future<Autogenerated> Suggsetionscontroller() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    final value = prefs.get('token') ?? 0;
    var response = await http.get(
      Uri.parse('http://192.168.1.108:8000/api/suggestion_and_complaint'),
      headers: {'Authorization': 'Bearer $value'
      },

    );


    if (response.statusCode == 200) {
      print(await response.body);


      final responsedata = jsonDecode(response.body);
      final Autogenerated suggsetions = Autogenerated.fromJson(responsedata);

return suggsetions;
    }
    else {
      throw Exception(' alan and fadi ');
    }

  }

