class Suggsetions_model{
  int? id;
  String? message;
  int? userId;
  String? createdAt;
  String? updatedAt;
String? complaint;
  Suggsetions_model(
  {this.id, this.message, this.userId, this.createdAt, this.updatedAt,this.complaint});

  Suggsetions_model.fromJson(Map<dynamic, dynamic> json) {
  id = json['id'];
  complaint = json['complaint'];
  message = json['suggestion']??"complaint";
  userId = json['user_id'];
  createdAt = json['created_at'];
  updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
  final Map<String, dynamic> data = new Map<String, dynamic>();
  data['id'] = this.id;
  data['suggestion'] = this.message;
  data['user_id'] = this.userId;
  data['created_at'] = this.createdAt;
  data['updated_at'] = this.updatedAt;
  return data;
  }
  }
class Autogenerated {
  List<Suggsetions_model>? suggestions;

  Autogenerated({this.suggestions});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['suggestions'] != null) {
      suggestions = <Suggsetions_model>[];
      json['suggestions'].forEach((v) {
        suggestions!.add(new Suggsetions_model.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.suggestions != null) {
      data['suggestions'] = this.suggestions!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

